### PR TITLE
Added timer reset on custom training shot

### PR DESCRIPTION
**Pull request by Bakkes**
Loving the plugin! One addition I thought of was automatic timer reset when doing custom training so you don't have to wait after a reset. I've added some functionality so the timer gets reset when the ball is fired in custom training by hooking ```Function TAGame.GameEvent_GameEditor_TA.FireBalls```

Edit: I just saw you mentioned this in the Discord so maybe you've already implemented it locally, in that case just ignore this PR

### CODE REVIEW

**Comment by jpsarda** [comment]
Yes I already did something with event "Function TAGame.Car_TA.PostBeginPlay" in the method OnCarSpawn. It was not very easy to do because when the car spawn, it moves, and the timer starts when car moves. So what I did is that when the car spawn, I reset the timer very fast after the car touched the ground.

But maybe "TAGame.GameEvent_GameEditor_TA.FireBalls" is better event, when is it fired ? Did you test your commit in custom training and it works fine ?

**Comment by Bakkes** [comment]
```TAGame.GameEvent_GameEditor_TA.FireBalls``` is fired as soon as the ball is shot, which in custom training is as soon as the player starts driving/moving. I've used it in custom training for a bit and it seems to work fine.

**Comment by jpsarda** [comment]
Oh OK I see that's the perfect event for this, I'll test it a bit and merge it.

**Comment by kcolton** [comment]
DECLINE. Fake @Bakkes 

Just kidding
-your friendly neighborhood alpaca

great work @jpsarda!

**Comment by jpsarda** [comment]
Thx @kcolton , are you a plugin or bakkesmode developer ?

**Pull request merged**
